# Generated by Django 4.2.4 on 2023-08-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='New',
        ),
    ]
