# Generated by Django 4.2.5 on 2023-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_rename_post_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coImg', models.ImageField(upload_to='companyImg')),
            ],
        ),
    ]
