# Generated by Django 4.2.5 on 2023-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_companyimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimg',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
